export const NOTIFICATION_TYPES = {
    // Candidate Types
    APPLICATION_STATUS_UPDATED: "APPLICATION_STATUS_UPDATED",
    INTERVIEW_SCHEDULED: "INTERVIEW_SCHEDULED",
    INTERVIEW_CANCELLED: "INTERVIEW_CANCELLED",
    JOB_RECOMMENDED: "JOB_RECOMMENDED",
    RESUME_ANALYZED: "RESUME_ANALYZED",
    CHAT_MESSAGE: "CHAT_MESSAGE",
    SYSTEM_ANNOUNCEMENT: "SYSTEM_ANNOUNCEMENT",

    // Recruiter Types
    NEW_APPLICATION: "NEW_APPLICATION",
    NEW_MESSAGE: "NEW_MESSAGE",
    AI_MATCH_FOUND: "AI_MATCH_FOUND",
    INTERVIEW_RESPONSE: "INTERVIEW_RESPONSE",
    ADMIN_ALERT: "ADMIN_ALERT",
};
export default NOTIFICATION_TYPES;
