export const NOTIFICATION_TYPES = {
    NEW_APPLICATION: "NEW_APPLICATION",
    APPLICATION_SHORTLISTED: "APPLICATION_SHORTLISTED",
    APPLICATION_REJECTED: "APPLICATION_REJECTED",
    INTERVIEW_SCHEDULED: "INTERVIEW_SCHEDULED",
    INTERVIEW_UPDATED: "INTERVIEW_UPDATED",
    INTERVIEW_CANCELLED: "INTERVIEW_CANCELLED",
    NEW_JOB_MATCH: "NEW_JOB_MATCH",
    SYSTEM_ANNOUNCEMENT: "SYSTEM_ANNOUNCEMENT",
    ADMIN_ALERT: "ADMIN_ALERT",
};
